models/Cursos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cursos".
 *
 * @property int $id
 * @property string $nombre
 * @property string $especialidad
 * @property string $nivel
 * @property string $dirigido
 * @property string $modalidad
 * @property string $turno
 * @property string $cartel
 * @property string $informacion
 *
 * @property Matriculas[] $matriculas
 * @property Alumnos[] $alumnos
 */
class Cursos extends \yii\db\ActiveRecord {

    public $actualizarCartel;
    public $actualizarInformacion;
    
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'cursos';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['nombre', 'especialidad', 'nivel', 'dirigido', 'modalidad', 'turno'], 'string', 'max' => 255],
            [['cartel'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['informacion'], 'file', 'skipOnEmpty' => true, 'extensions' => 'pdf'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'especialidad' => 'Especialidad',
            'nivel' => 'Nivel',
            'dirigido' => 'Dirigido',
            'modalidad' => 'Modalidad',
            'turno' => 'Turno',
            'cartel' => 'Cartel',
            'informacion' => 'Informacion',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMatriculas() {
        return $this->hasMany(Matriculas::className(), ['curso' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlumnos() {
        return $this->hasMany(Alumnos::className(), ['id' => 'alumno'])->viaTable('matriculas', ['curso' => 'id']);
    }

    public function beforeSave($insert) {
        /* voy a utilizar estas dos propiedades para saber si el usuario a actualizado los ficheros subidos*/
        $this->actualizarInformacion=TRUE;
        $this->actualizarCartel=TRUE;
        /* si no ha subido ningun fichero recupero el valor anterior de los ficheros */
        if(!isset($this->informacion)){
            $this->informacion=$this->getOldAttribute("informacion");
            $this->actualizarInformacion=FALSE;
        }
        if(!isset($this->cartel)){
            $this->cartel=$this->getOldAttribute("cartel");
            $this->actualizarCartel=FALSE;
        }
        return true;
    }
    
    

    public function afterSave($insert, $changeAttributes) {

        /* comprobar si ha seleccionado algun archivo */
        /* ademas comprobamos que sea un fichero lo que me llegue*/
        /* esto es para que si estoy borrando no me de problemas */
        /* llegaria un string en ese caso */
        
        if($this->actualizarInformacion && is_object($this->informacion)){
            //crear directorio
            \yii\helpers\FileHelper::createDirectory('imgs/informacion/' . $this->id , 0775, false);
            $this->informacion->saveAs('imgs/informacion/' . $this->id . "/" . iconv('UTF-8','ISO-8859-1',$this->informacion->name), false);
            $this->informacion = $this->informacion->name;
        }
        
        /* comprobar si ha seleccionado algun archivo */
        /* ademas comprobamos que sea un fichero lo que me llegue*/
        /* esto es para que si estoy borrando no me de problemas */
        /* llegaria un string en ese caso */
        if($this->actualizarCartel && is_object($this->cartel)){
            //crear directorio
            \yii\helpers\FileHelper::createDirectory('imgs/cartel/' . $this->id , 0775, false);
            // la funcion iconv la utilizo para que saveAs no me de problemas con las tildes y ñ
            $this->cartel->saveAs('imgs/cartel/' . $this->id . "/" . iconv('UTF-8','ISO-8859-1',$this->cartel->name), false);
            $this->cartel = $this->cartel->name;
        }
        //almacenar los cambios
        $this->updateAttributes(["informacion","cartel"]);
    }

    public function getCartel() {
        return Yii::$app->request->getBaseUrl() . '/imgs/cartel/' . $this->id . "/" . $this->cartel;
    }

    public function getInformacion() {
        return Yii::$app->request->getBaseUrl() . '/imgs/informacion/' . $this->id . "/" . $this->informacion;
    }

}

controllers/CursosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cursos;
use app\models\CursosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\web\UploadedFile;

/**
 * CursosController implements the CRUD actions for Cursos model.
 */
class CursosController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cursos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CursosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionListar()
    {
        
        $dataProvider = new ActiveDataProvider([
            'query' => Cursos::find(),
        ]);
       
        return $this->render('listar',[
            'dataProvider'=>$dataProvider,
        ]);
    }
    
    /**
     * Displays a single Cursos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cursos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

     public function actionCreate() {
        $model = new Cursos();

        if ($model->load(Yii::$app->request->post())) {
            $model->cartel = UploadedFile::getInstance($model, 'cartel');
            $model->informacion = UploadedFile::getInstance($model, 'informacion');
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }


    public function actionEliminar($id,$tipo){
        $model = $this->findModel($id);
        $model->$tipo="";
        $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
    }
    
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        if ($model->load(Yii::$app->request->post())) {
            // intentamos recuperar el fichero subido (actualizado)
            // en caso de que no seleccione ninguno el metodo estatico
            // devuelve null
            $model->cartel = UploadedFile::getInstance($model, 'cartel');
            $model->informacion = UploadedFile::getInstance($model, 'informacion');

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cursos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cursos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cursos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    /**
     * Nos permite realizar la subida de archivos
     * @return boolean
     */
    
    public function upload()
    {
        if ($this->validate()) {
            $this->foto->name=$this->nombre . $this->foto->name;
            $this->foto->saveAs('imgs/' . $this->foto->name,false);
            return true;
        } else {
            return false;
        }
    }
}

views/cursos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\Alert;

/* @var $this yii\web\View */
/* @var $model app\models\Cursos */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cursos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'especialidad')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nivel')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dirigido')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'modalidad')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'turno')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cartel')->fileInput() ?>

    <?php
    if (!empty($model->cartel)) {
        echo Alert::widget([
            'body' => Html::img($model->getCartel(), [
                'class' => 'img-responsive img-thumbnail',
            ]),
            'closeButton' => [
                'tag' => 'a',
                'href' => \yii\helpers\Url::to(['cursos/eliminar', 'id' => $model->id, 'tipo' => 'cartel']),
            ],
        ]);
    }
    ?>

    <?= $form->field($model, 'informacion')->fileInput() ?>

    <?php
    if (!empty($model->informacion)) {
        echo Alert::widget([
            'body' => '<embed src="' . $model->getInformacion() . '" width="500" height="200">',
            'closeButton' => [
                'tag' => 'a',
                'href' => \yii\helpers\Url::to(['cursos/eliminar', 'id' => $model->id, 'tipo' => 'informacion']),
            ],
        ]);
    }
    ?>



    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cursos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CursosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cursos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'especialidad') ?>

    <?= $form->field($model, 'nivel') ?>

    <?= $form->field($model, 'dirigido') ?>

    <?php // echo $form->field($model, 'modalidad') ?>

    <?php // echo $form->field($model, 'turno') ?>

    <?php // echo $form->field($model, 'cartel') ?>

    <?php // echo $form->field($model, 'informacion') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cursos/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Cursos */

$this->title = 'Create Cursos';
$this->params['breadcrumbs'][] = ['label' => 'Cursos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cursos-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cursos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CursosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cursos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cursos-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Cursos', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'especialidad',
            'nivel',
            'dirigido',
            'modalidad',
            'turno',
            'cartel',
            'informacion',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/cursos/listar.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CursosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Listado de todos nuestros cursos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cursos-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'nombre',
            'especialidad',
            'nivel',
            'dirigido',
            'modalidad',
            'turno',
            // mostrar una imagen dentro del gridview
            [
                'attribute' => 'cartel',
                'format' => 'image',
                'value' => function ($model) {
                    return $model->getCartel('cartel');
                },
                'contentOptions' => ['class' => 'grid-imagen'],
            ],
            'informacion',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/cursos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cursos */

$this->title = 'Update Cursos: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Cursos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cursos-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cursos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cursos */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cursos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cursos-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'especialidad',
            'nivel',
            'dirigido',
            'modalidad',
            'turno',
            'cartel',
            'informacion',
        ],
    ]) ?>

</div>